sudo: false
dist: xenial
cache: 
  apt: true
  directories:
    - $HOME/.deps
notifications:
  email:
    recipients:
      mwagawsw@gmail.com
    on_success: change
    on_failure: always

matrix:
  include:
    - os: linux
      language: c++
      compiler: gcc
      env: QF_ARCH=x86_64 QF_CC=gcc
      addons:
        apt:
          sources:
            - kubuntu-backports
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - cmake
            - build-essential
            - libsdl2-dev
            - libopenal-dev
            - libjpeg8-dev
            - libvorbis-dev
            - libtheora-dev
            - libfreetype6-dev
            - zlib1g-dev
            - libcurl4-gnutls-dev
    - os: linux
      language: c++
      compiler: clang
      env: QF_ARCH=x86_64 QF_CC=clang
      addons:
        apt:
          packages:
            - clang
            - cmake
            - build-essential
            - libsdl2-dev
            - libopenal-dev
            - libjpeg8-dev
            - libvorbis-dev
            - libtheora-dev
            - libfreetype6-dev
            - zlib1g-dev
            - libcurl4-gnutls-dev

install:
  - if [[ "$QF_CC" == "clang" ]]; then export CC=clang CXX=clang++; fi
  - if [[ "$QF_CC" == "gcc" ]]; then export CC=gcc-7 CXX=g++-7; fi
  - cd "$TRAVIS_BUILD_DIR/source"
  - if [[ "$QF_CC" == "clang" ]]; then cmake -DQFUSION_APPLICATION_VERSION_HEADER=\"version.warsow.h\" .; fi
  - if [[ "$QF_CC" == "gcc" ]]; then cmake -DQFUSION_APPLICATION_VERSION_HEADER=\"version.warsow.h\" .; fi
  - cd "$TRAVIS_BUILD_DIR"

script:
  - cd source
  - if [[ "$QF_CC" == "clang" ]]; then make -j8; fi
  - if [[ "$QF_CC" == "gcc" ]]; then make -j8; fi
